pipeline {
    agent any

    parameters {
        string(name: 'DEPENDENCIES', defaultValue: ' ')
        string(name: 'SERVERS', defaultValue: ' ')
        string(name: 'BROKER_PARAMETERS', defaultValue: ' ')
    }

    stages {
        stage('Load Kafka_Broker') {
            steps {
              script {
                echo "Running broker deploy"
                def dependencies_arr = "${DEPENDENCIES}".split(",")
                def server_arr = "${SERVERS}".split(",")
                def broker_parameters = "${BROKER_PARAMETERS}".split(",")

                for (i in dependencies_arr) {
                  println "DEPENDENCIES ---> ${i}"
                }

                for (i in server_arr) {
                  println "SERVERS ---> ${i}"
                }

                for (i in broker_parameters) {
                  println "BROKER_PARAMETERS ---> ${i}"
                }

              }
            }
        }
    }
}
