---
- hosts: all
  become: yes
  gather_facts: no

  roles:
    # - ansible-role-create-kafka-connector
     - ansible-role-install-kafka
    # - ansible-role-install-zookeeper
    # - ansible-role-install-kafka-connector
    # - ansible-role-install-preparation
