pipeline {
    agent any

    parameters {
        string(name: 'SERVERS', defaultValue: ' ')
        string(name: 'KAFKA_CONNECTOR', defaultValue: ' ')
        string(name: 'BROKER_PARAMETERS')
    }

    stages {
        stage('Load Kafka_Broker') {
            steps {
              script {

//Read keyfile.txt and add values to mylistkey
                echo "Read key file"
                def mylistkey = []
                def filePath = readFile "templates/kafka/kafka-broker/ansible-role-install-kafka-connector/keyfile.txt"
                def keyfile = filePath.readLines()

                for (key in keyfile) {
                  mylistkey.add(key)
                }
//Add parameters from main Jenkinsfile
                echo "Running kafka-connector deploy"
                def server_arr = "${SERVERS}".split(",")
                def kafka_connector_parameters = "${KAFKA_CONNECTOR}".split(",")
                def mylistvalue = []
//Add user values to mylistvalue
                for (i in kafka_connector_parameters ) {
                  mylistvalue.add(i)
                }

//Create MAP where key=mylistkey valu=mylistvalue
                def values = [mylistkey,mylistvalue].transpose().collectEntries{[it[0],it[1]]} //user enter parameters -> type MAP
                println  "{mylistkey - > $mylistkey}"
                println  "{mylistvalue - > $mylistvalue}"
                println  "{values - > $values}"

//Send values to Ansible
                  ansiblePlaybook (
                    playbook: 'templates/kafka/kafka-broker/playbook.yml',
                    inventoryContent: "by-kafka1-vm-1-vpn.spnode.net",
                    disableHostKeyChecking: true,
                    extraVars: [
                      container_name: "{{ '$values.container_name | default('kafka-connector1-1') }}",
                      connector_dns_name: "{{ '$values.connector_dns_name | default('kafka-connector1-1.net') }}",
                      ip_internal: "{{ '$values.ip_internal' | default('172.17.0.1') }}",
                      connect_rest_port: "{{ '$values.connect_rest_port' | default('8083') }}",
                      ip_external: "{{ '$values.ip_external' | default('172.17.0.1') }}",
                      connect_advertised_port: "{{ '$values.connect_advertised_port' | default('28083') }}",
                      ip_monitoring: "{{ $values.ip_monitoring | default('172.17.0.1') }}",
                      monitoring_port: "{{ '$values.monitoring_port' | default('9202') }}",
                      connect_group_id: "{{ '$values.connect_group_id' | default('1') }}",
                      kafka_heap_opts: "{{ '$values.kafka_heap_opts' | default('1') }}",
                      connect_config_storage_replication_factor: "{{ '$values.connect_config_storage_replication_factor' | default('1') }}",
                      connect_offset_storage_replication_factor: "{{ '$values.connect_offset_storage_replication_factor' | default('1') }}",
                      connect_status_storage_replication_factor: "{{ '$values.connect_status_storage_replication_factor' | default('1') }}"
                    ]
                )
              }
            }
        }
    }
}
