vm_count = 7

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.provision "shell", path: "./scripts/install_python.sh"
  config.vm.provision "file", source: "./scripts/", destination: "/tmp/"

  (1..vm_count).each do |vm_pc|
    config.vm.define "k8s-#{vm_pc}" do |node|
      node.vm.hostname = "k8s-#{vm_pc}"
      node.vm.network "private_network", bridge: "vboxnet0", ip: "192.168.56.#{10+vm_pc}", type: "static"
      node.vm.network "public_network", bridge: "enp6s0"
      config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "2048"
        vb.cpus = "2"
      end
    end
  end
end
